---
name: Builder
on:  # yamllint disable-line rule:truthy
  push:
    tags: ['[0-9].[0-9]+*']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Build with packer
        run: |
          sudo apt list -a packer
          sudo apt install -y --no-install-recommends packer \
             qemu-system-x86 qemu-utils guestfs-tools genisoimage
          example_build/
          packer plugins install github.com/hashicorp/qemu
          PACKER_LOG=1 packer build -parallel-builds=1 deb11k6.json
          cd output; sha512sum deb11k6.qcow2 > SHA512SUMS
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            example_build/output/deb11k6.qcow2
            example_build/output/SHA512SUMS
